name: ml_autoencoders_env  # Choose a descriptive name for your environment
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11  # Replace with your desired Python version if different
  - pip
  - pip:
    - matplotlib==3.8.4
    - numpy==2.0.0
    - pandas==2.2.2
    - Pillow==10.3.0
    - pytorch_lightning==2.2.2
    - scikit_learn==1.4.2
    - seaborn==0.13.2
    - torchmetrics==1.3.2
    - wandb==0.17.0
  - pytorch==2.2.2
  - torchvision==0.17.2 
  - conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
